FROM 172.16.74.168/default/python:3.6.4
MAINTAINER Wenbao Xu<xuwenbao@chinacloud.com.cn>

WORKDIR /usr/src/app

ENV FLASK_APP app.py

LABEL support_extension="tar.gz"

ADD flaskr.tar.gz /usr/src/app/

#RUN apt-get install -y gcc libxml2-dev python-dev

RUN pip install --upgrade pip && \
    pip install -r requirements.txt -i https://pypi.douban.com/simple/

EXPOSE 8000

CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0", "--port", "8000"]